### ISSUE TITLE
Add Command abstraction

### ISSUE THREAD

**Issue by lordcodes** [lordcodes/turtle#120]
**Describe the problem**

Currently, commands are ran immediately as a function, being able to create a command that is kept in a structure would enable other things to be implemented using Turtle, such as a Pipeline feature in the future to run a set of commands in a sequence piping output into next command.

**Describe your solution**

Create a Command data class that contains the command and its arguments, that can then be executed later.

**Checklist**

- [X] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [X] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the feature.
- [X] I've checked there are no other [open issues](https://github.com/lordcodes/turtle/issues) for the same feature.

**Comment by lordcodes** [comment]
Thank you! I did actually intend to do this right after the merge. Will add this to my list to do tonight! 👍🏻

**Comment by lordcodes** [comment]
@jmfayard I released v0.8.0 last night, which includes the PRs you have contributed recently.

**Comment by jmfayard** [comment]
Awesome thanks
