### ISSUE TITLE
shellRun hangs if output is large

### ISSUE THREAD

**Issue by pwerry** [lordcodes/turtle#121]
**Describe the bug**
If the output of a shell command is really large then `shellRun` will hang

**Checklist**
- [x] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [x] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the issue.
- [x] I've checked there are no other [open issues](https://github.com/lordcodes/turtle/issues) for the same issue.

**To Reproduce**
run a command like `git cat-file -p origin/main:<some-big-file>`. In our case the file was a 4000 line long OpenAPI spec.

**Expected behavior**
Dumps file output

**Comment by lordcodes** [comment]
This likely relates to reading all the output into a String for the return value. There is an API within Turtle to run a command with streaming output, maybe this version needs to use for a command with a lot of output like this.

**Comment by lordcodes** [comment]
Closing, as the solution is to use the streaming API when there will be a lot of output.
