### ISSUE TITLE
set (or at least check) shell binary being used.  

### ISSUE THREAD

**Issue by unredundant** [lordcodes/turtle#171]
**Describe the problem**
Hey, tried to use this tool, but am running into a problem where commands are not found, despite them working in my shell.  I'm guessing that this library is picking up the wrong shell (maybe using bash, where as I am using ZSH)

**Describe your solution**
It's not clear to me how I validate this theory.  Being able to set (or at least look up) the path of the binary this library is using would be nice :) 

**Checklist**

- [x] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [x] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the feature.
- [x] I've checked there are no other [open issues](https://github.com/lordcodes/turtle/issues) for the same feature.

**Additional context**

**Comment by lordcodes** [comment]
It uses the built-in Kotlin/Java Process API. Surprised as I use ZSH and my co-worker uses Bash and we have Turtle running commands in some custom Gradle tasks on a shared project.

**Comment by lordcodes** [comment]
My gut feeling is it relates more to the context in which it is running commands than your shell. 

You could get Turtle to run some commands to print things like the PATH.

In terms of your feature request, commands are ram using the Kotlin Process API. Turtle isn't running the commands itself or selecting a particular shell itself.

**Comment by unredundant** [comment]
Makes sense, feel free to close this if you think there's no work to do :)

**Comment by unredundant** [comment]
ty for the speedy response btw
