### ISSUE TITLE
Use with android Studio

### ISSUE THREAD

**Issue by shalzz** [lordcodes/turtle#4]
Hi,

With the latest Android Studio 4.0 release, Android studio now has support for Kotlin DSL for gradle files.
I'm trying to use this project to run some git shell commands but can't get it to install. Are there any special instructions to get this gradle task to work with Android and Android Studio?
I've tried including the `implementation("com.lordcodes.turtle:turtle:0.2.0")` in both the module level build.gradle.kts as well as the app level build file as a classpath.

**Comment by shalzz** [comment]
It seems it does work with the `classpath` approach, I just had to manually import the shellRun command.
Sorry for the noise.

**Comment by lordcodes** [comment]
No problem. Thank you for your interest in Turtle. Let me know if you need
any more help or have any recommendations for improvements.
