### ISSUE TITLE
Mock ShellScript within tests

### ISSUE THREAD

**Issue by jefpij** [lordcodes/turtle#97]
**Describe the problem**
I have an application with multiple layers (ui, interactor, repository, service). The ui layer; although cmdline, is the layer where I use ShellScript. I want each layer to be testable independently which means layers or their constructor arguments will need to be mocked in order to keep it as isolated as possible. Shellscript, being an final class with internal constructor, cannot be given passed as a constructor argument. This makes writing isolated unit tests impossible in my setup.

**Describe your solution**
Appending the keyword 'open' will solve this.

**Checklist**

- [ x ] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [ x ] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the feature.
- [ x ] I've checked there are no other [open issues](https://github.com/lordcodes/turtle/issues) for the same feature.

**Additional context**
None

**Comment by jefpij** [comment]
Pull request can be found: https://github.com/lordcodes/turtle/pull/98/commits

**Comment by jefpij** [comment]
Thank you for reaching out! 
I've attempted to create a wrapper around it but am not succeeding. Would you be willing to give a pointer in the right direction perhaps?


I've created a small snippet to demonstrate where I am stuck and concluded that the "open" keyword was required.

```
import com.lordcodes.turtle.shellRun
import java.io.File

class ShellScriptWrapper(val workingDirectory: File? = null, script: ShellScriptWrapper.() -> String) {
    
    fun command(command: String, arguments: List<String> = listOf()) {
        shellRun(workingDirectory) {
            command(command = command, arguments = arguments)
        }
    }

}
```

So the general plan is to inject this ShellScriptWrapper as a constructor parameter in my layers to mock it. The problem I am facing is that by using this approach I can only use ShellScript through the shellRun method. ShellScript has an internal constructor so I cannot create an instance of it within my wrapper.

Being forced to use shellRun, a new instance of ShellScript will be made for each call to command. Needless to say this isn't ideal when wanting to execute multiple commands. 

Ideally I would want to create an internal ShellScript instance within my wrapper class and use it with the command-method for instance. 

In addition when for instance wrapping ShellScriptWrapper.command() around ShellScript.command(), there is also use of specific callbacks (ProcessCallbacks). Would you recommend wrapping an interface around that interface as well as to uphold separation?

Thank you.

**Comment by jefpij** [comment]
I like the convenient shellRun functionality a lot. Having to create a wrapper around the shellRun to actually wrap ShellScript doesn't produce the best readable setup, to be honest. It also takes away the ease of use as demonstrated with this library.

Furthermore I agree with the rest.
I noticed you've already updated the code base. 

Thank you and great job on the library!

**Comment by lordcodes** [comment]
Yes I agree. 'shellRun' is designed for use directly really, to run commands. For example, I use it within custom Gradle tasks.

However, as you said when use within a codebase such as you are describing, it is better to use ShellScript so you have a little more control and in this case the constructor really needed to be public, which has been merged.

I will aim to get a release out as soon as I can.

Thank you, I am very glad to hear it is useful for someone 😄

**Comment by lordcodes** [comment]
@jefpij New release is out with an accessible constructor.

**Comment by jefpij** [comment]
Thank you!
